# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(help_text='When the service should start')),
                ('end_at', models.DateTimeField(help_text='When the service should end')),
                ('address', models.CharField(help_text='Service address', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Special instructions for the provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current booking status', max_length=12)),
                ('total_price', models.PositiveIntegerField(help_text='Total price in AOA including extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('extras', models.ManyToManyField(blank=True, help_text='Additional services/add-ons', related_name='bookings_extras', to='services.servicetask')),
                ('provider', models.ForeignKey(blank=True, help_text='Provider assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('service_task', models.ForeignKey(help_text='Main service task for this booking', on_delete=django.db.models.deletion.PROTECT, to='services.servicetask')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Rating score from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the service')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(help_text='Booking being rated', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created'],
            },
        ),
    ]
