# Generated by Django 5.2.4 on 2025-09-21 10:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours worked (for hourly services)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_pending',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount pending after service', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_prepaid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid at booking time', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='credits_consumed',
            field=models.PositiveIntegerField(default=1, help_text='Number of package credits consumed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount after service completion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_used',
            field=models.ForeignKey(blank=True, help_text='Package used for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workers.servicepackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property_typology',
            field=models.ForeignKey(blank=True, help_text='Property type for typology-based pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.propertytypology'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units (e.g., AC units)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker assigned to this booking (new system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workers.worker'),
        ),
    ]
