# Generated by Django 5.2.4 on 2025-09-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_actual_hours_booking_amount_pending_and_more'),
        ('workers', '0002_migrate_provider_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='provider',
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workers.worker'),
        ),
    ]
