# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('booking', 'Booking Services'), ('payments', 'Payments & Billing'), ('providers', 'For Providers'), ('account', 'Account Management'), ('troubleshooting', 'Troubleshooting'), ('policies', 'Policies')], help_text='Help article category', max_length=60)),
                ('title', models.CharField(help_text='Article title', max_length=160)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('body_md', models.TextField(help_text='Article content in Markdown format')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this article')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the article is visible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Article',
                'verbose_name_plural': 'Help Articles',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug for the page', unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=120)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('body_md', models.TextField(help_text='Page content in Markdown format')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the page is visible')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Whether to show link in footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=180)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('excerpt', models.CharField(help_text='Brief description for previews', max_length=255)),
                ('body_md', models.TextField(help_text='Blog post content in Markdown format')),
                ('hero_image', models.ImageField(help_text='Featured image for the blog post', upload_to='blog/')),
                ('category', models.CharField(choices=[('news', 'News'), ('tips', 'Tips & Tricks'), ('updates', 'Updates'), ('guides', 'Guides'), ('company', 'Company')], default='news', help_text='Blog post category', max_length=50)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date and time')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the post is visible to the public')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this post')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of the blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published'],
            },
        ),
    ]
