version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-staging
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Zela.settings.staging
      - DEBUG=False
    env_file:
      - .env.staging
    depends_on:
      - db
      - redis
    volumes:
      - ../Zela/media:/app/media
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: zela_staging
      POSTGRES_USER: zela
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_staging:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - ../Zela/staticfiles:/var/www/static
      - ../Zela/media:/var/www/media
      - ../ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data_staging:
  redis_data_staging:
