# Generated by Django 5.2.4 on 2025-07-19 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('apple', 'Apple Pay')], help_text='Type of payment method', max_length=20)),
                ('provider_id', models.CharField(help_text='External provider ID (e.g. Stripe PM token)', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc)', max_length=20)),
                ('last4', models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField(blank=True, help_text='Card expiry month (1-12)', null=True)),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, help_text='Card expiry year', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-added_at'],
                'unique_together': {('user', 'provider_id')},
            },
        ),
    ]
