# Generated by Django 5.2.4 on 2025-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='accepts_same_day',
            field=models.BooleanField(default=True, help_text='Whether provider accepts same-day bookings'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Job completion rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether provider is currently available for work'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='jobs_completed',
            field=models.PositiveIntegerField(default=0, help_text='Total number of completed jobs'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='jobs_total',
            field=models.PositiveIntegerField(default=0, help_text='Total number of jobs assigned'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total earnings from all completed jobs', max_digits=10),
        ),
    ]
