# Generated by Django 5.2.4 on 2025-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_providerprofile_accepts_same_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='avoid_tolls',
            field=models.BooleanField(default=False, help_text='Avoid toll roads when possible'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='include_traffic_time',
            field=models.BooleanField(default=True, help_text='Include traffic time in travel estimates'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='max_travel_distance',
            field=models.PositiveIntegerField(default=25, help_text='Maximum travel distance in kilometers'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='prefer_main_roads',
            field=models.BooleanField(default=True, help_text='Prefer main roads over shortcuts'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='preferred_radius',
            field=models.PositiveIntegerField(default=15, help_text='Preferred working radius in kilometers'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list, help_text='List of service areas with surcharges'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly working hours schedule'),
        ),
    ]
