# Generated by Django 5.2.4 on 2025-07-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_providerprofile_avoid_tolls_and_more'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(help_text='Starting location/neighborhood', max_length=255)),
                ('to_location', models.CharField(help_text='Service location/neighborhood', max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=1, help_text='Distance in kilometers', max_digits=5)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, help_text='Distance surcharge amount', max_digits=10)),
                ('service_name', models.CharField(help_text='Service requested', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', help_text='Request status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking if accepted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_request', to='bookings.booking')),
                ('provider', models.ForeignKey(help_text='Provider who received this request', on_delete=django.db.models.deletion.CASCADE, related_name='distance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distance Request',
                'verbose_name_plural': 'Distance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
