# Generated by Django 5.2.4 on 2025-07-20 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_distancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID number', max_length=50),
        ),
        migrations.CreateModel(
            name='ProviderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('service_agreement', 'Service Provider Agreement'), ('privacy_policy', 'Privacy Policy'), ('terms_service', 'Terms of Service'), ('nda', 'Non-Disclosure Agreement'), ('commission_agreement', 'Commission Agreement')], help_text='Type of contract', max_length=30)),
                ('title', models.CharField(help_text='Contract title', max_length=255)),
                ('version', models.CharField(help_text='Contract version', max_length=10)),
                ('file', models.FileField(help_text='Contract PDF file', upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('acknowledged', 'Acknowledged'), ('expired', 'Expired')], default='pending', help_text='Contract status', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, help_text='When the contract was signed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when signed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Contract expiry date', null=True)),
                ('provider', models.ForeignKey(help_text='Provider who signed this contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'Provider Contract',
                'verbose_name_plural': 'Provider Contracts',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'contract_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('proof_address', 'Proof of Address'), ('bank_statement', 'Bank Statement'), ('criminal_record', 'Criminal Record Check'), ('insurance', 'Insurance Certificate'), ('license', 'Professional License'), ('other', 'Other Document')], help_text='Type of document', max_length=20)),
                ('file', models.FileField(help_text='Document file', upload_to='kyc_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Document verification status', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is required')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('provider', models.ForeignKey(help_text='Provider who owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.providerprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Document',
                'verbose_name_plural': 'Provider Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('provider', 'document_type')},
            },
        ),
    ]
