# Generated by Django 5.2.4 on 2025-07-20 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_address_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_alerts', models.BooleanField(default=True, help_text='Get notified when new jobs match your preferences')),
                ('payment_alerts', models.BooleanField(default=True, help_text='Notifications about payments and payouts')),
                ('weekly_reports', models.BooleanField(default=True, help_text='Summary of your weekly performance')),
                ('push_notifications', models.BooleanField(default=True, help_text='App notifications on your mobile device')),
                ('system_updates', models.BooleanField(default=True, help_text='Important system updates and maintenance')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('customers', 'Customers Only'), ('private', 'Private')], default='public', help_text='Control who can see your profile information', max_length=20)),
                ('share_location', models.BooleanField(default=True, help_text='Allow customers to see your approximate location')),
                ('share_statistics', models.BooleanField(default=False, help_text='Share your performance statistics')),
                ('allow_reviews', models.BooleanField(default=True, help_text='Let customers leave reviews on your profile')),
                ('data_collection', models.BooleanField(default=True, help_text='Allow Zela to collect usage data for improvements')),
                ('auto_accept_jobs', models.BooleanField(default=False, help_text='Automatically accept jobs that match your criteria')),
                ('max_jobs_per_day', models.CharField(default='5', help_text="Maximum jobs per day (number or 'unlimited')", max_length=10)),
                ('preferred_job_types', models.JSONField(blank=True, default=list, help_text='List of preferred job types')),
                ('minimum_job_value', models.DecimalField(decimal_places=2, default=100, help_text='Minimum job value in AOA', max_digits=10)),
                ('travel_radius', models.PositiveIntegerField(default=15, help_text='Travel radius in kilometers')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('fr', 'Français')], default='pt', help_text='Preferred language', max_length=5)),
                ('timezone', models.CharField(default='Africa/Luanda', help_text='Preferred timezone', max_length=50)),
                ('currency', models.CharField(choices=[('AOA', 'Kwanza (AOA)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='AOA', help_text='Preferred currency', max_length=3)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='App theme', max_length=10)),
                ('map_view', models.CharField(choices=[('standard', 'Standard'), ('satellite', 'Satellite'), ('hybrid', 'Hybrid')], default='satellite', help_text='Preferred map view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account for these settings', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
