# Generated by Django 5.2.4 on 2025-09-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersettings'),
        ('workers', '0002_migrate_provider_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancerequest',
            name='provider',
        ),
        migrations.AddField(
            model_name='distancerequest',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker who received this request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distance_requests', to='workers.worker'),
        ),
    ]
