# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'House Cleaning')", max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('icon', models.CharField(help_text="Heroicon/Lucide icon key (e.g., 'home', 'wrench')", max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('description', models.TextField(blank=True, help_text='Optional description for the category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Task name (e.g., 'Deep Clean', 'Basic Clean')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('price', models.PositiveIntegerField(help_text='Base price in AOA (Angolan Kwanza)')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='Estimated duration in hours', max_digits=4)),
                ('is_addon', models.BooleanField(default=False, help_text='Whether this task is an add-on service')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task is available for booking')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Service category this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Task',
                'verbose_name_plural': 'Service Tasks',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
