# Generated by Django 5.2.4 on 2025-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='booking_requirements',
            field=models.JSONField(blank=True, default=dict, help_text="Special requirements for booking, e.g. {'minimum_hours': 2, 'requires_property_type': true}"),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='pricing_model',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('hourly_min', 'Hourly with Minimum'), ('per_unit', 'Per Unit Pricing'), ('package', 'Package/Credits'), ('typology', 'Property-Based')], default='fixed', help_text='Default pricing model for this category', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='worker_model_type',
            field=models.CharField(blank=True, choices=[('CleaningWorker', 'Cleaning Worker'), ('ElectricianWorker', 'Electrician'), ('ACTechnicianWorker', 'AC Technician'), ('PestControlWorker', 'Pest Control'), ('DogTrainerWorker', 'Dog Trainer'), ('HandymanWorker', 'Handyman'), ('GardenerWorker', 'Gardener'), ('PlacementWorker', 'Placement Worker')], help_text='Type of worker model for this category', max_length=50),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='certification_requirements',
            field=models.JSONField(blank=True, default=list, help_text='Required certifications'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='equipment_requirements',
            field=models.JSONField(blank=True, default=list, help_text="Required equipment, e.g. ['diagnostic_tools', 'cleaning_supplies']"),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='pricing_config',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible pricing configuration based on pricing model'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='pricing_model',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('hourly_min', 'Hourly with Minimum'), ('per_unit', 'Per Unit Pricing'), ('package', 'Package/Credits'), ('typology', 'Property-Based')], help_text='Override category pricing model for this task', max_length=20),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='skill_requirements',
            field=models.JSONField(blank=True, default=list, help_text="Required skills for workers, e.g. ['electrical_license', 'hvac_cert']"),
        ),
    ]
