# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=120)),
                ('message', models.CharField(help_text='Notification message', max_length=255)),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('rating', 'Rating'), ('system', 'System'), ('promotion', 'Promotion'), ('reminder', 'Reminder')], default='system', help_text='Type of notification', max_length=20)),
                ('link', models.CharField(blank=True, help_text='Optional link when notification is clicked', max_length=255)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_important', models.BooleanField(default=False, help_text='Whether this is an important notification')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('user', models.ForeignKey(help_text='User who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
