# Generated by Django 5.2.4 on 2025-09-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_booking_requirements_and_more'),
        ('workers', '0002_migrate_provider_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, help_text="Whether worker's ability to provide this service is verified")),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority for this worker in this service category (higher = better match)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(help_text='Service category the worker can provide', on_delete=django.db.models.deletion.CASCADE, related_name='worker_services', to='services.servicecategory')),
                ('worker', models.ForeignKey(help_text='Worker who can provide this service', on_delete=django.db.models.deletion.CASCADE, related_name='worker_services', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Worker Service',
                'verbose_name_plural': 'Worker Services',
                'ordering': ['-priority', 'created_at'],
                'unique_together': {('worker', 'service_category')},
            },
        ),
        migrations.CreateModel(
            name='WorkerServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_config', models.JSONField(default=dict, help_text='Custom pricing configuration overriding service defaults')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Markup percentage above base price (-50 to +200)', max_digits=5)),
                ('minimum_price', models.PositiveIntegerField(blank=True, help_text='Minimum price for this worker-service combination', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom pricing is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_service', models.OneToOneField(help_text='Worker-service relationship this pricing applies to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='workers.workerservice')),
            ],
            options={
                'verbose_name': 'Worker Service Pricing',
                'verbose_name_plural': 'Worker Service Pricing',
            },
        ),
    ]
