# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Payment gateway reference ID', max_length=120, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Payment amount in AOA')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer')], help_text='Payment gateway used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', help_text='Current payment status', max_length=20)),
                ('gateway_response', models.JSONField(default=dict, help_text='Raw response from payment gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Booking this payment is for', on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('provider', models.ForeignKey(blank=True, help_text='Provider who will receive payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start date of the week being paid out')),
                ('week_end', models.DateField(help_text='End date of the week being paid out')),
                ('amount', models.PositiveIntegerField(help_text='Payout amount in AOA')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='Platform commission rate (e.g., 0.15 for 15%)', max_digits=5)),
                ('commission_amount', models.PositiveIntegerField(help_text='Commission amount deducted')),
                ('net_amount', models.PositiveIntegerField(help_text='Net amount paid to provider')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Payout status', max_length=20)),
                ('is_disbursed', models.BooleanField(default=False, help_text='Whether payout has been disbursed')),
                ('disbursement_reference', models.CharField(blank=True, help_text='Bank transfer reference', max_length=120)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the payout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_at', models.DateTimeField(blank=True, help_text='When the payout was disbursed', null=True)),
                ('provider', models.ForeignKey(help_text='Provider receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-week_start'],
                'unique_together': {('provider', 'week_start')},
            },
        ),
    ]
