# Generated by Django 5.2.4 on 2025-07-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout'), ('refund', 'Refund'), ('commission', 'Commission'), ('adjustment', 'Adjustment'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], help_text='Type of transaction', max_length=20)),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=120, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Transaction amount in AOA')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Transaction status', max_length=20)),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('payout', models.ForeignKey(blank=True, help_text='Related payout record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payout')),
                ('user', models.ForeignKey(help_text='User associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='recent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Transaction',
                'verbose_name_plural': 'Recent Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_re_user_id_b27dc9_idx'), models.Index(fields=['transaction_type', 'status'], name='payments_re_transac_9397e0_idx')],
            },
        ),
    ]
