# Generated by Django 5.2.4 on 2025-09-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_recenttransaction_transaction_type_and_more'),
    ]

    operations = [
        # Clear unique_together constraints first
        migrations.AlterUniqueTogether(
            name='earningshistory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together=set(),
        ),
    ]
