# Generated by Django 5.2.4 on 2025-09-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_clear_unique_constraints'),
        ('workers', '0003_workerservice_workerservicepricing'),
    ]

    operations = [
        # First add worker fields
        migrations.AddField(
            model_name='earningshistory',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker who earned this', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings_history', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker who will receive payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='payout',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker receiving the payout', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker requesting payout', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='providerwallet',
            name='worker',
            field=models.OneToOneField(blank=True, help_text='Worker who owns this wallet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='workers.worker'),
        ),
        # Remove old provider fields
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='providerwallet',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='earningshistory',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='provider',
        ),
        # Finally set unique_together constraints
        migrations.AlterUniqueTogether(
            name='earningshistory',
            unique_together={('worker', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together={('worker', 'week_start')},
        ),
    ]
