# Generated by Django 5.2.3 on 2025-07-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('nanny', 'Nanny'), ('housekeeper', 'Housekeeper'), ('elder_care', 'Elder Care'), ('cook', 'Cook'), ('gardener', 'Gardener'), ('driver', 'Driver'), ('general_helper', 'General Helper')], help_text='Type of placement needed', max_length=40)),
                ('live_in', models.BooleanField(help_text='Whether the placement is live-in')),
                ('start_date', models.DateField(help_text='When the placement should start')),
                ('location', models.CharField(help_text='Location where services will be provided', max_length=255)),
                ('budget_min', models.PositiveIntegerField(help_text='Minimum budget in AOA per month')),
                ('budget_max', models.PositiveIntegerField(help_text='Maximum budget in AOA per month')),
                ('requirements', models.TextField(help_text='Specific requirements and preferences')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special instructions')),
                ('status', models.CharField(choices=[('open', 'Open'), ('shortlist_sent', 'Shortlist Sent'), ('interview_scheduled', 'Interview Scheduled'), ('contracted', 'Contracted'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', help_text='Current status of the inquiry', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Urgency level of the placement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer making the inquiry', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Inquiry',
                'verbose_name_plural': 'Placement Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
