# Generated by Django 5.2.3 on 2025-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_clean_base', models.PositiveIntegerField(default=4900, help_text='Base hourly rate for cleaning services in AOA')),
                ('specialty_task_price', models.PositiveIntegerField(default=3000, help_text='Price for specialty tasks in AOA')),
                ('outdoor_min_price', models.PositiveIntegerField(default=9000, help_text='Minimum price for outdoor services in AOA')),
                ('placement_fee_domestic', models.PositiveIntegerField(default=65000, help_text='Placement fee for domestic workers in AOA')),
                ('placement_fee_nanny', models.PositiveIntegerField(default=85000, help_text='Placement fee for nannies in AOA')),
                ('booking_fee', models.PositiveIntegerField(default=500, help_text='Booking fee in AOA')),
                ('cancellation_fee', models.PositiveIntegerField(default=2000, help_text='Cancellation fee in AOA')),
                ('provider_commission_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='Commission rate for providers (e.g., 0.15 for 15%)', max_digits=5)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.2, help_text='Weekend service price multiplier', max_digits=3)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Holiday service price multiplier', max_digits=3)),
                ('minimum_booking_amount', models.PositiveIntegerField(default=5000, help_text='Minimum booking amount in AOA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
    ]
